# .github/workflows/ci-cd.yml
name: publish-pypi

on:
  workflow_call:
    inputs:
      pypi_repository_url:
        required: true
        type: string
    secrets:
      pypi_api_token:
        required: true

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/azure-simple-email
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install pypa/build
      run: python -m pip install build twine --upgrade --user
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Check with twine
      run: twine check dist/*
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_api_token }}
        repository_url: ${{ inputs.pypi_repository_url }}